"""Add location fields to food_stands

Revision ID: add_location_fields
Revises: 6bf6e0ba2edc
Create Date: 2025-08-13 06:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_location_fields'
down_revision = '6bf6e0ba2edc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_stands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('municipality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('postal_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_stands', schema=None) as batch_op:
        batch_op.drop_column('postal_code')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('state')
        batch_op.drop_column('municipality')

    # ### end Alembic commands ###
